DMVM-197(feat): send user data to web view
PBTP/Mongle_iOS pull request #21
Opened 2024-09-18 14:05 UTC by bulmang

## 🎫 지라 티켓 이슈
[()](https://dogbusiness.atlassian.net/browse/DMVM-197?atlOrigin=eyJpIjoiZTc2YzA2OGI4NmU1NGJlMDliYTUxNDBlZGUxZTQ4YmEiLCJwIjoiaiJ9)
<br>

<br>

## 🛠️ 작업 내용

<br>

<br>

## 📱 작업 화면

|화면 이름|스크린샷|
|:--:|:--:|
|ViewName|<img src = "" width ="250">|

<br>

## 🗒️ Note (optional)

2024-11-13 12:30 UTC, VictoryJu commented
쿠키 형태로 보내는것이 안전하고 확실한것같습니다! 고생하셨습니다 감사해요~~

2024-11-13 12:30 UTC, VictoryJu approved these changes

2024-11-14 12:25 UTC, bokoo14 requested changes

2024-11-14 12:25 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/ChatView.swift
> +import Core
```suggestion
import Core
import SwiftUI
```

import문은 알파벳 순으로 정렬해주세요

2024-11-14 12:25 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .secure: "TRUE"
제가 질문 드렸던 부분 중에 HTTPCookie클래스에서 http로도 통신이 되는지 물어봤었는데, 찾아보니 .secure부분을 true로 설정하면 https연결에서만 전송됩니다!

> HTTPCookie를 생성할 때, secure 속성을 설정할 수 있습니다. 이 속성은 해당 쿠키가 HTTPS 프로토콜에서만 전송되어야 한다는 것을 의미합니다.
secure = true로 설정된 쿠키는 HTTPS 연결에서만 전송됩니다.
secure = false로 설정된 쿠키는 HTTP 및 HTTPS 연결 모두에서 전송됩니다.

2024-11-14 12:25 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/WebEventController.swift
> +    }
테스트용 코드이면 주석으로 표시해주세용

2024-11-14 12:25 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/WebEventController.swift
> +    if message.name == "webviewInit" {
이 값은 웹쪽에서 주는 메시지 명일까요?? 
잘몰라서 물어봅니다 ㅎㅎ
웹과 논의되어 설정한 name값인지 궁금합니다

2024-11-14 12:25 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .path: "/",
path는 왜 비어있는지 궁금합니다.
예를 들면 다른 부분에서 웹뷰를 사용한다면 path부분이 /chat, /info 등의 path를 사용하는 것이 적절하다 생각이 듭니다

2024-11-14 12:25 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +    private static func createWebView(_ webEventController: WebEventController, kakaoAuthCore: KaKaoAuthCore) -> WKWebView {
웹뷰를 여러 군데에서 사용하는 것이라면 재사용성 및 유지보수의 용이를 위해 웹뷰 관련 메서드들은 한 곳에 모아 관리하는 것이 어떨까요??
ex) 웹뷰 관리 클리스 또는 웹뷰 유틸리티 클래스

2024-11-14 12:25 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +        guard let cookie = HTTPCookie(properties: [
🍪

2024-11-14 14:51 UTC, VictoryJu commented on Mongle/Projects/Features/ChatFeature/Sources/WebEventController.swift
> +    if message.name == "webviewInit" {
@bokoo14  쿠키 도입이전에 webviewInit 함수로 웹에서 유저 데이터 초기값을 설정하였는데, 현재는 사용하지않고있습니다.

2024-11-14 15:16 UTC, VictoryJu commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .path: "/",
웹뷰쪽 기능들이 대부분 인증정보가 필요해서 (예약,채팅,결제 등등)
모든 페이지에서 사용하기 편하게 "/" 경로로 지정해주신것같습니다

2024-11-15 02:29 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/WebEventController.swift
> +    if message.name == "webviewInit" {
현재는 사용하지 않는 기능이라면 제거 부탁드립니다.
@bulmang

2024-11-15 02:44 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .path: "/",
@bulmang 웹에 쿠키 설정이 필요없는 부분이 있을테니 해당 메서드에 path를 인자로 받아 설정하여 사용하는 것이 어떨까요?
해당 부분 웹에서 추가 작업이 필요할까요?

2024-11-15 08:10 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/ChatView.swift
> +import Core
suggestion commit 감사합니다! 반영하게요

2024-11-15 08:12 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .path: "/",
`웹에 쿠키 설정이 필요없는 부분이 있을테니` 이 부분은 @VictoryJu님이 말씀해주시면 좋을 것 같습니다. 필요없는 부분이 있을까요?

2024-11-15 08:12 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .secure: "TRUE"
좋은 정보 감사합니다~!

2024-11-15 08:12 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/WebEventController.swift
> +    if message.name == "webviewInit" {
네 이번 PR에서 Front 개발자님이 1번, 2번 테스트 해보시고 1번으로 정해주셔서 2번 기능은 제거하겠습니다~!

2024-11-15 08:15 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +    private static func createWebView(_ webEventController: WebEventController, kakaoAuthCore: KaKaoAuthCore) -> WKWebView {
오 한번 고민 해보겠습니다!

2024-11-15 08:21 UTC, VictoryJu commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .path: "/",
/location 페이지(주소검색) 제외한 나머지 페이지들은 전부 필요합니다

2024-11-15 08:23 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/WebEventController.swift
> +    }
Front 개발자분께서 테스트 하실 수 있게 만든 코드입니다.
1번 쿠키로 토큰 전달을 선택하셔서 삭제하겠습니다~!

2024-11-15 08:25 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .path: "/",
> @bulmang /location 페이지(주소검색) 제외한 나머지 페이지들은 전부 필요합니다

location 페이지(주소검색)는 토큰 없이도 접속이 가능할까요?

2024-11-15 08:31 UTC, VictoryJu commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +            .path: "/",
> > @bulmang /location 페이지(주소검색) 제외한 나머지 페이지들은 전부 필요합니다
> 
> location 페이지(주소검색)는 토큰 없이도 접속이 가능할까요?

넹 주소 검색 시에는 토큰이 필요하지 않아서 

해당 페이지는 토큰 없어도 문제 없이 접속 가능합니다.

2024-11-15 09:30 UTC, bulmang commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +    private static func createWebView(_ webEventController: WebEventController, kakaoAuthCore: KaKaoAuthCore) -> WKWebView {
> 웹뷰를 여러 군데에서 사용하는 것이라면 재사용성 및 유지보수의 용이를 위해 웹뷰 관련 메서드들은 한 곳에 모아 관리하는 것이 어떨까요?? ex) 웹뷰 관리 클리스 또는 웹뷰 유틸리티 클래스

추후에 웹뷰를 여러개 생성했을때 웹뷰 관리 클래스를 생성하는 것이 어떨까요?
현재는 1~2개의 웹뷰 밖에 없는 상황이라 더 많은 웹뷰들이 있을때 여러 케이스를 관리할 수 있는 클래스를 만드는 것이 좋아보입니다.

2024-11-17 07:10 UTC, bokoo14 commented on Mongle/Projects/Features/ChatFeature/Sources/ChatWebUIView.swift
> +    private static func createWebView(_ webEventController: WebEventController, kakaoAuthCore: KaKaoAuthCore) -> WKWebView {
넵 좋습니당

2024-11-18 02:05 UTC, merged

2024-11-24 15:36 UTC, bokoo14 commented
저도 approve하고 싶어요 ..

2024-11-25 04:58 UTC, bulmang commented
규칙 만들게요!
@bokoo14

2024-11-25 13:46 UTC, bokoo14 commented
승인하려고 했는데 먼저 merge하신듯ㅎㅎ

2024-11-25 13:49 UTC, bulmang commented
디코에 완료 전환 안내했는데 확인 이모지 눌러주셔서 머지했어요!