DMVM-192(feat): navigation 구현
PBTP/Mongle_iOS pull request #22
Opened 2024-11-24 15:34 UTC by bokoo14

## 🎫 지라 티켓 이슈
좀이따 쓸게요 .. 
<br>

<br>

## 🛠️ 작업 내용

<br>

<br>

## 📱 작업 화면

|화면 이름|스크린샷|
|:--:|:--:|
|ViewName|<img src = "" width ="250">|

<br>

## 🗒️ Note (optional)

2024-12-03 02:17 UTC, bulmang commented
정말 잘 쓰여진 PR입니다!!👍 저도 꼼꼼하게 보고 저의 의견을 남기겠습니다.😄
읽는 도중에 문제가 있는 부분이 있어 먼저 말씀드립니다!

> ⚠️
> [Step1] 이미지에 저희 카카오톡 앱 키가 보여지고 있습니다.
> 혹시 블로그나 다른 공개된 곳에 올려져 있다면 내려주세요.

확인하시고 수정하시면 답변부탁드려요!

2024-12-03 04:33 UTC, bulmang requested changes
정말 많은 작업을 해주셨어요!
고생많으셨습니다!!!

Navigation 부분은 제가 이어받아 추가작업을 진행하도록 할게요!

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/Features/HomeFeature/Sources/HomeView/HomeView.swift
```swift
#Preview {
    NavigationStack {
        HomeView()
    }
}
```
네비게이션 기능이 연결이 되었으므로 Preview에서도 네비게이션 기능을 확인할 수 있게 `NavigationStack`을 넣어주면 어떨까요?

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/App/Sources/MainView.swift
> +    @StateObject var navigationVM = NavigationViewModel(path: [])
NavigationViewModel에 path를 빈배열로 초기화 시키는 것을 인스턴스화 하는 과정에서 하는 것이 아닌
생성할때 빈 배열로 초기화시키면 가독성이 좋을 것 같습니다.

## 예시
### MainView
**`@StateObject var navigationVM = NavigationViewModel()`**

### NavigationViewModel
```swift
    public init(path: [Screen] = []) {
        self.path = path
    }
```

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/App/Sources/MainView.swift
> +                } // openURL
이건 개인의 생각에 따라 다를 것 같은데 가독성을 봤을 때 긴 modifier를 맨 밑으로 가면 어떨까요?
저희가 modifier 규칙을 정하면 좋을 것 같아요!
```suggestion
                .environmentObject(navigationVM)
                .onOpenURL { url in
                    navigationVM.handleDeeplink(url: url)
                } // openURL
               .navigationDestination(for: Screen.self) { route in
                    switch route {
                    case .home:
                        HomeView()
                    case .searchCompany:
                        SearchView()
                    case .storeDetail:
                        Text("test")
                    case .notification:
                        NotificationView()
                    }
                } // navigationDestination
```

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/Features/HomeFeature/Sources/HomeView/CompoanyList/CompanyListItem.swift
UI를 구성하는 구조체들은 한칸씩 개행하는거 어떨까요?

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/Features/HomeFeature/Sources/NotificationView/NotificationListItem.swift
struct Notification: Identifiable { } 을 해서 
ForEach(notifications) { notification in  { } 을 하는 방법도 있는데 따로 hashable하는 이유가 있는지 궁금합니다!
어떤 방법이 좋은지 저도 잘몰라서 질문드려요

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/Features/HomeFeature/Sources/NotificationView/NotificationView.swift
> +        .navigationBarBackButtonHidden(true)
UINavigationController를 사용한다면 마찬가지로 제거가 필요합니다.

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/Features/ProfileFeature/Sources/ProfileView.swift
마찬가지로 한칸씩 개행하는거 어떠신가요? 이것도 회의하여 규칙을 정하면 좋겠네요!

2024-12-03 04:33 UTC, bulmang commented on Mongle/Projects/Ui/Sources/HeaderComponent/TabHeaderComponent.swift
>      }
아래 코드로 하면 문제없이 작동됩니다. 기본값으로 EmptiyView()를 넣어서 생성자 코드를 한번만 작성해도 됩니다.
```swift
    public init(
        headerText: String,
        firstIconImageName: Image? = nil,
        firstDestination: FirstDestination = EmptyView(),
        secondIconName: Image? = nil,
        secondDestination: SecondDestination = EmptyView()
    ) {
        self.headerText = headerText
        self.firstIconImageName = firstIconImageName
        self.firstDestination = firstDestination
        self.secondIconName = secondIconName
        self.secondDestination = secondDestination
    }
```

2024-12-03 04:38 UTC, bokoo14 commented
> 정말 잘 쓰여진 PR입니다!!👍 저도 꼼꼼하게 보고 저의 의견을 남기겠습니다.😄 읽는 도중에 문제가 있는 부분이 있어 먼저 말씀드립니다!
> 
> > ⚠️
> > [Step1] 이미지에 저희 카카오톡 앱 키가 보여지고 있습니다.
> > 혹시 블로그나 다른 공개된 곳에 올려져 있다면 내려주세요.
> 
> 확인하시고 수정하시면 답변부탁드려요!

수정했어용

2024-12-03 04:38 UTC, bokoo14 commented
> 정말 많은 작업을 해주셨어요! 고생많으셨습니다!!!
> 
> Navigation 부분은 제가 이어받아 추가작업을 진행하도록 할게요!

오~~ 기대하고 있습니다 ㅎㅎ

2024-12-06 07:05 UTC, bokoo14 commented on Mongle/Projects/Features/HomeFeature/Sources/HomeView/HomeView.swift
반영했습니다~

2024-12-06 07:31 UTC, bokoo14 commented on Mongle/Projects/Features/HomeFeature/Sources/HomeView/CompoanyList/CompanyListItem.swift
이게 무슨 말일까요?

2024-12-06 08:12 UTC, bokoo14 commented on Mongle/Projects/App/Sources/MainView.swift
> +    @StateObject var navigationVM = NavigationViewModel(path: [])
반영했습니다

2024-12-06 08:15 UTC, bulmang commented on Mongle/Projects/Features/HomeFeature/Sources/HomeView/CompoanyList/CompanyListItem.swift
Lint 이야기 인데 저희 한 번 이야기 해봐요!

2024-12-20 14:32 UTC, bulmang approved these changes

2024-12-20 14:34 UTC, bulmang commented on Mongle/Projects/Core/Sources/Views/UINavigationController.swift
테스트 하셨을때 따로 문제 없었을까요?

2024-12-29 12:23 UTC, merged

2024-12-29 13:34 UTC, bokoo14 commented
테스트

2024-12-29 13:37 UTC, bokoo14 commented
제 댓글이 pending되어 다시 댓글 남깁니다..  PR이 merged되어 해당 댓글을 어떻게 살려보려했는데 실패했습니다 ㅜ

> 이건 개인의 생각에 따라 다를 것 같은데 가독성을 봤을 때 긴 modifier를 맨 밑으로 가면 어떨까요? 저희가 modifier 규칙을 정하면 좋을 것 같아요!

![스크린샷 2024-12-29 오후 10 36 26](https://github.com/user-attachments/assets/e0f6bc11-0446-4768-a6c8-a85314762c09)

2024-12-29 13:38 UTC, bokoo14 commented
@bulmang 

![스크린샷 2024-12-29 오후 10 37 39](https://github.com/user-attachments/assets/3f6102f4-7272-4f88-8146-bc9419b525fb)

2024-12-29 13:39 UTC, bokoo14 commented
@bulmang 
![스크린샷 2024-12-29 오후 10 37 59](https://github.com/user-attachments/assets/8bcbd8e3-0b77-4ed1-b714-d206a0323118)

2024-12-29 13:39 UTC, bokoo14 commented
@bulmang 
![스크린샷 2024-12-29 오후 10 38 23](https://github.com/user-attachments/assets/1b6172dc-2104-4d6b-adf2-d6dd6e8eec7a)

2024-12-29 13:40 UTC, bokoo14 commented
@bulmang 
이전에 달았던 댓글이 pending되어 있는데 PR이 merged되면서 해당 댓글이 pending상태에서 어떻게 변경이 안되네요 ㅜㅜ
이거 이것저것 찾아봤는데 고칠 수 없는듯하여서 그냥 댓글 남겼던 부분 캡쳐하여서 comment 다시 남겼습니다 ㅜ 
해결방법 아시면 알려주세요 ㅜㅜ